name: Build unstable image

on:
  workflow_call: 
    inputs:
      docker_context: 
        type: string
        default: "."
        required: false
      dockerfile:
        type: string
        default: Dockerfile.prod
        required: false
      image_name:
        type: string
        required: true
        description: The base name of the image.
    secrets:
      GH_PACKAGE_READ_TOKEN:
        required: true

jobs:
  build_unstable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: ${{ inputs.docker_context }}
        file: ${{ inputs.dockerfile }}
        secrets: |
          "gh_package_read_token=${{ secrets.GH_PACKAGE_READ_TOKEN }}"
        push: true
        tags: | 
           ghcr.io/mlibrary/${{ inputs.image_name }}-unstable:latest
           ghcr.io/mlibrary/${{ inputs.image_name }}-unstable:${{ github.sha }}


