name: Deploy

on:
  workflow_call: 
    inputs:
      image:
        type: string
        required: true
        description: The full gchr image
      file:
        type: string
        required: true
        description: path to file in repository to update with the image 
      CONFIG_REPO_RW_APP_ID:
        type: string
        required: true
      CONFIG_REPO_RW_INSTALL_ID:
        required: true
        type: string
      CONFIG_REPO_FULL_NAME:
        required: true
        type: string
    secrets:
      CONFIG_REPO_RW_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate app token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ inputs.CONFIG_REPO_RW_APP_ID }}
        installation_id: ${{ inputs.CONFIG_REPO_RW_INSTALL_ID }}
        private_key: ${{ secrets.CONFIG_REPO_RW_KEY }}
    - name: Send the message
      uses: peter-evans/repository-dispatch@v2
      with:
        event-type: update-image
        token: ${{ steps.generate_token.outputs.token }}
        repository: ${{ inputs.CONFIG_REPO_FULL_NAME }}
        client-payload: '{
          "subject": "Update ${{ inputs.file }}",
          "body": "Originating repository is ${{ github.repository }}\nRun ID is $GITHUB_RUN_ID\nUser is ${{ github.actor }}",
          "image": "${{ inputs.image }}",
          "file": "${{ inputs.file }}"
        }'
