name: Deploy

on:
  workflow_call: 
    inputs:
      image:
        type: string
        required: true
        description: The full gchr image
      file:
        type: string
        required: true
        description: path to file in repository to update with the image 
      CONFIG_REPO_RW_APP_ID:
        type: string
        required: true
      CONFIG_REPO_RW_INSTALL_ID:
        required: false
        type: string
      CONFIG_REPO_FULL_NAME:
        required: true
        type: string
    secrets:
      CONFIG_REPO_RW_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate app token
      id: generate_token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.CONFIG_REPO_RW_APP_ID }}
        private-key: ${{ secrets.CONFIG_REPO_RW_KEY }}
        owner: ${{ github.repository_owner }}
    - name: Send the message
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: update-image
        token: ${{ steps.generate_token.outputs.token }}
        repository: ${{ inputs.CONFIG_REPO_FULL_NAME }}
        client-payload: '{
          "subject": "Update ${{ inputs.file }}",
          "body": "Originating repository is ${{ github.repository }}\nRun ID is ${{ github.run_id }}\nUser is ${{ github.actor }}",
          "image": "${{ inputs.image }}",
          "file": "${{ inputs.file }}"
        }'
